apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharpdevops1-deployment
  labels:
    app: csharpdevops1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharpdevops1
  template:
    metadata:
      labels:
        app: csharpdevops1
    spec:
      containers:
      - name: csharpdevops1
        image: srcmkr/csharpdevopsdemo
        env:
        - name: COLOR
          value: "#6601b2"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: csharpdevops1
  name: csharpdevops1-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: csharpdevops1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-csharpdevops1
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: demo1.d3v.to
    http:
      paths:
      - path: /
        backend:
          serviceName: csharpdevops1-service
          servicePort: 80