apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: prometheus
  name: ingress-grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: monitoring.d3v.to
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus-grafana
          servicePort: 80